// This file needs the REST Client extension installed in order to work.
// You can install it from the Visual Studio Code marketplace.

GET http://localhost:5266/games

###

GET http://localhost:5266/games/2

###

POST http://localhost:5266/games
Content-Type: application/json

{
    "title": "Super Mario Bros. Wonder",
    "genreId": 3,
    "price": 59.99,
    "releaseDate": "2023-10-20"
}

###

POST http://localhost:5266/games
Content-Type: application/json

{
    "title": "Street Fighter 2",
    "genreId": 1,
    "price": 9.99,
    "releaseDate": "1991-02-01"
}

###

PUT http://localhost:5266/games/2
Content-Type: application/json

{
    "title": "Street Fighter II Turbo",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "1992-07-15"
}

###

DELETE http://localhost:5266/games/3

###

GET http://localhost:5266/genres

###

GET http://localhost:5266/hello

